# Generated by Django 4.2.6 on 2024-04-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_created_at_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='groupproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.groupproduct'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='datetime_price_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
